edition = "2018"
fn_params_layout = "Compressed"
format_strings = true
match_block_trailing_comma = true
spaces_around_ranges = true
use_try_shorthand = true
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
format_code_in_doc_comments = true
fn_single_line = true